# 服务名称
spring:
  application:
    name: sys-eureka
# 服务端口号
server:
  port: 8761

#Eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
    # 是否从其他的服务中心同步服务列表
    fetchRegistry: false
    # 是否把自己作为服务注册到其他服务注册中心
    registerWithEureka: false
